# -*- coding: utf-8 -*-
"""Phi-SOC Module B — Pipeline Unificado (versão publicável)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlFHRYkdliNrqPS3Stl-Jl7xZgc9TuG9
"""

# pipeline_completo.py (v3.1 — correcções de blindagem para publicação)
"""
Phi-SOC Module B — Pipeline Unificado (versão publicável)
==========================================================
Inclui:
  - identificação dinâmica da dimensão ativa no sweep de parâmetros
  - ligação explícita entre F_lie (geométrico) e C_red (Poisson efectivo)
  - validação da natureza quasi‑Lie por comparação com baseline
  - documentação dos limites da aproximação linear das derivadas
"""

import torch
import torch.optim as optim
import numpy as np
import networkx as nx
import random
from collections import deque

# ----------------------------------------------------------------------
# Configuração global
# ----------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DTYPE = torch.float64

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

# ============================================================================
# 1. Geração de grafos e acoplamento
# ============================================================================
def generate_graph(N, m=2, seed=None):
    if seed is not None:
        G = nx.barabasi_albert_graph(N, m, seed=seed)
    else:
        G = nx.barabasi_albert_graph(N, m)
    return G

def generate_graphs(sizes, m=2, seed=42):
    set_seed(seed)
    graphs_raw = []
    for g, size in enumerate(sizes):
        G = nx.barabasi_albert_graph(size, m, seed=seed + g*1000)
        mapping = {old: f"G{g}_{old}" for old in G.nodes()}
        G = nx.relabel_nodes(G, mapping)
        graphs_raw.append(G)
    return graphs_raw

def add_cross_edges(G_global, graphs_raw, num_edges, edge_signs=None, seed=42):
    rng = np.random.RandomState(seed)
    nodes0 = list(graphs_raw[0].nodes())
    nodes1 = list(graphs_raw[1].nodes())
    if edge_signs is None:
        edge_signs = {}
    added = 0
    while added < num_edges:
        u = rng.choice(nodes0)
        v = rng.choice(nodes1)
        if not G_global.has_edge(u, v):
            G_global.add_edge(u, v)
            s = rng.choice([1, -1])
            edge_signs[(u, v)] = s
            edge_signs[(v, u)] = s
            added += 1
    return G_global, edge_signs

def couple_graphs(G_list, cross_edges_per_pair=5, seed=42):
    G_global = nx.Graph()
    for G in G_list:
        G_global = nx.compose(G_global, G)
    num_graphs = len(G_list)
    nodes_per_graph = [sorted(list(G.nodes())) for G in G_list]
    node_graph = {}
    for g, nodes in enumerate(nodes_per_graph):
        for node in nodes:
            node_graph[node] = g
    rng = np.random.RandomState(seed)
    for g1 in range(num_graphs):
        for g2 in range(g1+1, num_graphs):
            for _ in range(cross_edges_per_pair):
                u = rng.choice(nodes_per_graph[g1])
                v = rng.choice(nodes_per_graph[g2])
                if not G_global.has_edge(u, v):
                    G_global.add_edge(u, v)
    return G_global, node_graph, nodes_per_graph

def generate_and_couple_graphs(sizes, m=2, cross_edges_per_pair=5, seed=42):
    graphs_raw = generate_graphs(sizes, m, seed)
    G_global, node_graph, nodes_per_graph = couple_graphs(graphs_raw, cross_edges_per_pair, seed)
    return G_global, node_graph, nodes_per_graph, graphs_raw

# ============================================================================
# 2. Ciclos e clusters
# ============================================================================
def find_fundamental_cycles(G):
    T = nx.bfs_tree(G, source=list(G.nodes())[0])
    T_undirected = T.to_undirected()
    cycles = []
    for (u, v) in G.edges():
        if not T_undirected.has_edge(u, v):
            try:
                path = nx.shortest_path(T_undirected, u, v)
                edges = [(path[k], path[k+1]) for k in range(len(path)-1)]
                edges.append((v, u))
                cycles.append(edges)
            except:
                pass
    return cycles

def select_cluster(G, cycles, max_size=64):
    hub = max(G.degree, key=lambda x: x[1])[0]
    cluster = [c for c in cycles if any(hub in e for e in c)]
    return cluster[:max_size]

def build_clusters(cycles_list, max_per_graph=30):
    clusters = [sorted(c, key=len, reverse=True)[:max_per_graph] for c in cycles_list]
    all_cycles, cycle_to_graph = [], []
    for g, cl in enumerate(clusters):
        for cycle in cl:
            all_cycles.append(cycle)
            cycle_to_graph.append(g)
    return clusters, all_cycles, cycle_to_graph

# ============================================================================
# 3. Mapas de arestas e tensores geométricos
# ============================================================================
def canonical_edge(u, v):
    return (min(u, v), max(u, v))

def build_edge_maps(cycles, edge_signs=None):
    maps = []
    for cycle in cycles:
        m = {}
        for (u, v) in cycle:
            key = canonical_edge(u, v)
            base_sign = 1 if (u, v) == key else -1
            s = (edge_signs.get((u, v), edge_signs.get((v, u), 1)) if edge_signs else 1)
            m[key] = base_sign * s
        maps.append(m)
    return maps

def compute_F_raw(edge_maps, avg_weight=None, cycle_to_graph=None,
                  EPSILON_BLOCK=0.01, normalize=True):
    """
    Tensor de tripla interseção F_raw[i,j,k].
    EPSILON_BLOCK controla a mistura entre ciclos de grafos diferentes.
    Se normalize=True, o tensor é normalizado pelo máximo absoluto (geométrico).
    """
    K = len(edge_maps)
    F = torch.zeros((K, K, K), device=device, dtype=DTYPE)
    edge_to_cycles = {}
    for i, m in enumerate(edge_maps):
        for e in m:
            edge_to_cycles.setdefault(e, []).append(i)
    for e, idxs in edge_to_cycles.items():
        w = avg_weight.get(e, 1.0) if avg_weight else 1.0
        for i in idxs:
            for j in idxs:
                for k in idxs:
                    val = edge_maps[i][e] * edge_maps[j][e] * edge_maps[k][e] * w
                    if cycle_to_graph is not None:
                        gi, gj, gk = cycle_to_graph[i], cycle_to_graph[j], cycle_to_graph[k]
                        if gi != gj or gj != gk:
                            val *= EPSILON_BLOCK
                    F[i, j, k] += val
    if normalize:
        mx = F.abs().max()
        if mx > 0:
            F /= mx
    return F

def compute_metric_intersection(edge_maps):
    K = len(edge_maps)
    g = torch.zeros((K, K), device=device, dtype=DTYPE)
    for i in range(K):
        for j in range(K):
            g[i, j] = len(set(edge_maps[i]) & set(edge_maps[j]))
    mx = g.abs().max()
    if mx > 0:
        g /= mx
    return g

def compute_metric_covariance(S_series):
    g_np = np.cov(S_series.T)
    g = torch.tensor(g_np, dtype=DTYPE, device=device)
    g = g + 1e-4 * torch.eye(g.shape[0], device=device, dtype=DTYPE)
    g = g / torch.trace(g)
    return g

# ============================================================================
# 4. Simulação SOC unificada
# ============================================================================
default_SOC_params = {
    'm': 2, 'threshold_base': 2.0, 'a_SOC': 0.08, 'b_SOC': 0.04,
    'c_SOC': 0.03, 'eta_lambda': 0.02, 'alpha_smooth': 0.05,
    'GAMMA_COMPETITION': 0.005, 'MAX_TENSION': 1e6
}

def run_soc_simulation(G_global, node_graph, nodes_per_graph,
                       EPSILON_CROSS=0.01, T_equil=3000, T_sample=10000,
                       snap_interval=200, dissipative=True, adaptive_lambda=True,
                       frustration=False, tear_prob=0.0, inversion_prob=0.0,
                       add_edge_prob=0.0, competition_strength=0.0,
                       max_avalanche_size=None, seed=42, **kwargs):
    m = kwargs.get('m', default_SOC_params['m'])
    b_SOC = kwargs.get('b_SOC', default_SOC_params['b_SOC'])
    a_SOC = kwargs.get('a_SOC', default_SOC_params['a_SOC'])
    c_SOC = kwargs.get('c_SOC', default_SOC_params['c_SOC'])
    threshold_base = kwargs.get('threshold_base', default_SOC_params['threshold_base'])
    eta_lambda = kwargs.get('eta_lambda', default_SOC_params['eta_lambda'])
    alpha_smooth = kwargs.get('alpha_smooth', default_SOC_params['alpha_smooth'])
    GAMMA_COMPETITION = kwargs.get('GAMMA_COMPETITION', default_SOC_params['GAMMA_COMPETITION'])
    MAX_TENSION = kwargs.get('MAX_TENSION', default_SOC_params['MAX_TENSION'])

    set_seed(seed)
    rng = np.random.RandomState(seed)

    num_graphs = len(nodes_per_graph)
    all_nodes = list(G_global.nodes())
    deg = dict(G_global.degree())
    deg_internal = {}
    for node in all_nodes:
        g = node_graph[node]
        deg_internal[node] = max(1, sum(1 for n in G_global.neighbors(node)
                                        if node_graph.get(n) == g))

    tension = [np.zeros(len(nodes_per_graph[g])) for g in range(num_graphs)]
    lambda_block = np.ones(num_graphs)
    R0_block = np.ones(num_graphs)
    local_idx = [{node: i for i, node in enumerate(nodes_per_graph[g])}
                 for g in range(num_graphs)]

    edge_weight_sum = {e: 0.0 for e in G_global.edges()}
    edge_weight_sum.update({(v, u): 0.0 for (u, v) in G_global.edges()})
    snapshots = []

    node_signs = [np.ones(len(nodes_per_graph[g])) for g in range(num_graphs)]
    host_internal_edges = []
    if frustration:
        for g in range(num_graphs):
            for i in range(len(nodes_per_graph[g])):
                if rng.random() < 0.2:
                    node_signs[g][i] = -1.0
        host_internal_edges = [(u, v) for (u, v) in G_global.edges()
                               if node_graph[u] == 1 and node_graph[v] == 1]

    def run_avalanche(start_node):
        g_start = node_graph[start_node]
        start_local = local_idx[g_start][start_node]
        queue = deque([(start_node, g_start, start_local)])
        visited = set([start_node])
        total_topplings = 0
        while queue and (max_avalanche_size is None or total_topplings < max_avalanche_size):
            node_i, g_i, i_local = queue.popleft()
            total_topplings += 1
            for neighbor in G_global.neighbors(node_i):
                g_j = node_graph.get(neighbor, -1)
                if g_j == -1:
                    continue
                j_local = local_idx[g_j][neighbor]
                transfer = (0.3 + b_SOC * lambda_block[g_i]) * tension[g_i][i_local] / deg_internal[node_i]
                if frustration:
                    transfer *= node_signs[g_i][i_local] * node_signs[g_j][j_local]
                if g_i != g_j:
                    transfer *= EPSILON_CROSS
                if frustration and g_i == 0 and g_j == 1:
                    if tear_prob > 0 and len(host_internal_edges) > m * len(nodes_per_graph[1]) // 2:
                        if rng.random() < tear_prob:
                            incident = [e for e in host_internal_edges if neighbor in e]
                            if len(incident) > 0:
                                e_remove = incident[rng.randint(0, len(incident))]
                                if G_global.has_edge(*e_remove):
                                    G_global.remove_edge(*e_remove)
                                    host_internal_edges.remove(e_remove)
                                    for v in e_remove:
                                        deg_internal[v] = max(1, sum(1 for n in G_global.neighbors(v) if node_graph.get(n) == 1))
                                    if rng.random() < inversion_prob:
                                        node_signs[g_j][j_local] *= -1.0
                elif g_i == 1 and g_j == 0:
                    transfer *= 0.01
                tension[g_j][j_local] += transfer
                tension[g_j][j_local] = min(tension[g_j][j_local], MAX_TENSION)
                edge_weight_sum[(node_i, neighbor)] += transfer
                edge_weight_sum[(neighbor, node_i)] += transfer
                if dissipative:
                    thresh = threshold_base * deg[neighbor] / (1 + a_SOC * lambda_block[g_j])
                    if g_j == 1:
                        thresh *= deg[neighbor] ** 0.5
                    if tension[g_j][j_local] > thresh and neighbor not in visited:
                        visited.add(neighbor)
                        queue.append((neighbor, g_j, j_local))
                else:
                    if neighbor not in visited:
                        visited.add(neighbor)
                        queue.append((neighbor, g_j, j_local))
            if dissipative:
                tension[g_i][i_local] *= 0.1 / (1 + c_SOC * lambda_block[g_i])
            tension[g_i][i_local] = min(tension[g_i][i_local], MAX_TENSION)
        return total_topplings, len(visited)

    for t in range(T_equil + T_sample):
        if competition_strength > 0:
            for i in range(min(len(nodes_per_graph[0]), len(nodes_per_graph[1]))):
                tension[0][i] -= competition_strength * tension[1][i]
                tension[1][i] -= competition_strength * tension[0][i]
                tension[0][i] = max(0.0, tension[0][i])
                tension[1][i] = max(0.0, tension[1][i])
        if add_edge_prob > 0 and rng.random() < add_edge_prob:
            u = rng.choice(nodes_per_graph[0])
            v = rng.choice(nodes_per_graph[1])
            if not G_global.has_edge(u, v):
                G_global.add_edge(u, v)
                s = rng.choice([1, -1])
                edge_weight_sum[(u, v)] = 0.0
                edge_weight_sum[(v, u)] = 0.0
                deg[u] = G_global.degree(u)
                deg[v] = G_global.degree(v)
                deg_internal[u] = max(1, sum(1 for n in G_global.neighbors(u) if node_graph.get(n) == 0))
                deg_internal[v] = max(1, sum(1 for n in G_global.neighbors(v) if node_graph.get(n) == 1))
        g = rng.randint(num_graphs)
        u = rng.choice(nodes_per_graph[g])
        i_local = local_idx[g][u]
        tension[g][i_local] += lambda_block[g] * (node_signs[g][i_local] if frustration else 1.0)
        tension[g][i_local] = min(abs(tension[g][i_local]), MAX_TENSION) * np.sign(tension[g][i_local])
        threshold = threshold_base * deg[u] / (1 + a_SOC * lambda_block[g])
        trigger = (abs(tension[g][i_local]) > threshold) if frustration else (tension[g][i_local] > threshold)
        if trigger:
            size, unique = run_avalanche(u)
            if adaptive_lambda:
                R0_current = size / unique if size > 1 else 0.0
                R0_block[g] = (1 - alpha_smooth) * R0_block[g] + alpha_smooth * R0_current
                lambda_block[g] += eta_lambda * (1.0 - R0_block[g])
                lambda_block[g] = max(0.01, lambda_block[g])
                mean_R0 = np.mean(R0_block)
                for k in range(num_graphs):
                    lambda_block[k] += GAMMA_COMPETITION * (R0_block[k] - mean_R0)
                    lambda_block[k] = max(0.01, lambda_block[k])
        if t == T_equil:
            for e in edge_weight_sum:
                edge_weight_sum[e] = 0.0
        if t >= T_equil and (t - T_equil) % snap_interval == 0:
            snap = {e: edge_weight_sum[e] for e in G_global.edges()}
            snap.update({(v, u): edge_weight_sum[(v, u)] for (u, v) in G_global.edges()})
            snapshots.append(snap)
    return snapshots, lambda_block, R0_block

# ============================================================================
# 5. Observação: séries temporais e pesos médios
# ============================================================================
def compute_S_series(clusters, all_cycles, cycle_to_graph, edge_maps, snapshots):
    K = len(all_cycles)
    n_snaps = len(snapshots)
    S = np.zeros((n_snaps, K))
    offset = 0
    for cluster in clusters:
        k = len(cluster)
        for sn, snap in enumerate(snapshots):
            for idx, cycle_map in enumerate(edge_maps[offset:offset+k]):
                for e, sign in cycle_map.items():
                    S[sn, offset+idx] += sign * snap.get(e, 0.0)
        offset += k
    return S

def compute_avg_weights_from_snapshots(snapshots):
    avg_weight = {}
    if not snapshots:
        return avg_weight
    for e in snapshots[0]:
        vals = [snap.get(e, 0.0) for snap in snapshots]
        avg_weight[e] = np.mean(vals)
    max_w = max(avg_weight.values()) if avg_weight else 1.0
    if max_w > 0:
        for e in avg_weight:
            avg_weight[e] /= max_w
    return avg_weight

# ============================================================================
# 6. Inferência: métrica, tensor F e tensor de Lie
# ============================================================================
def compute_F_lie(F_raw, g):
    """
    Tensor de Lie linearizado (colchete de Poisson efectivo geométrico).
    F_lie = g * F_raw - permutações.
    """
    return torch.einsum('jm, imk -> ijk', g, F_raw) - torch.einsum('im, jmk -> ijk', g, F_raw)

def build_SOC_tensors(snapshots, clusters, all_cycles, cycle_to_graph,
                      edge_maps, EPSILON_BLOCK=0.01):
    S_series = compute_S_series(clusters, all_cycles, cycle_to_graph, edge_maps, snapshots)
    avg_weight = compute_avg_weights_from_snapshots(snapshots)
    F_raw = compute_F_raw(edge_maps, avg_weight, cycle_to_graph, EPSILON_BLOCK, normalize=True)

    K = len(all_cycles)
    S_blocks = []
    offset = 0
    for cluster in clusters:
        k = len(cluster)
        S_blocks.append(S_series[:, offset:offset+k])
        offset += k
    g_np = np.zeros((K, K))
    offsets = [0]
    for S_blk in S_blocks:
        k = S_blk.shape[1]
        blk_cov = np.cov(S_blk.T)
        g_np[offsets[-1]:offsets[-1]+k, offsets[-1]:offsets[-1]+k] = blk_cov
        offsets.append(offsets[-1] + k)
    g = torch.tensor(g_np, dtype=DTYPE, device=device)
    g = g + 1e-4 * torch.eye(K, device=device, dtype=DTYPE)
    g = g / torch.trace(g)
    F_lie = compute_F_lie(F_raw, g)
    return S_series, F_raw, g, F_lie, offsets

# ============================================================================
# 7. Parêntesis de Poisson empírico
# ============================================================================
def poisson_bracket_omega(S_series):
    n_snaps, K = S_series.shape
    omega = np.zeros((K, K))
    for t in range(n_snaps - 1):
        x = S_series[t]
        dx = S_series[t+1] - S_series[t]
        omega += np.outer(x, dx) - np.outer(dx, x)
    omega /= (n_snaps - 1)
    return (omega - omega.T) / 2

def estimate_derivatives_C(S_series, lambda_reg=1e-4, window=10):
    """
    Estima ∂_k ω^{ij} por regressão linear com regularização Ridge.
    Nota: a aproximação linear despreza cumulantes de ordem superior;
    a violação residual de Jacobi pode reflectir essas não‑linearidades.
    """
    n_snaps, K = S_series.shape
    X_w, Y_w = [], []
    for t in range(0, n_snaps - window, window):
        sub = S_series[t:t+window]
        w = poisson_bracket_omega(sub)
        X_w.append(sub.mean(axis=0))
        Y_w.append(w.flatten())
    if len(X_w) < K:
        X_w = [S_series.mean(axis=0)]
        Y_w = [poisson_bracket_omega(S_series).flatten()]
    X_arr, Y_arr = np.array(X_w), np.array(Y_w)
    XtX = X_arr.T @ X_arr + lambda_reg * np.eye(K)
    XtY = X_arr.T @ Y_arr
    C_flat = np.linalg.solve(XtX, XtY).T
    return C_flat.reshape(K, K, K)

def poisson_jacobi_direct(omega, C):
    K = omega.shape[0]
    J = np.zeros((K, K, K))
    for i in range(K):
        for j in range(K):
            for k in range(K):
                s = 0.0
                for l in range(K):
                    s += (omega[i, l] * C[j, k, l] +
                          omega[j, l] * C[k, i, l] +
                          omega[k, l] * C[i, j, l])
                J[i, j, k] = s
    norm_J = np.sum(J**2)
    norm_omega = np.sum(omega**2)
    norm_C = np.sum(C**2)
    return norm_J / (norm_omega * norm_C + 1e-8)

def shuffle_baseline(S_series, seed=None):
    rng = np.random.RandomState(seed)
    idx = rng.permutation(S_series.shape[0])
    S_shuffled = S_series[idx]
    omega_sh = poisson_bracket_omega(S_shuffled)
    C_sh = estimate_derivatives_C(S_shuffled)
    return poisson_jacobi_direct(omega_sh, C_sh)

# ============================================================================
# 8. Álgebras de Lie de referência
# ============================================================================
def chevalley_tensor(algebra='A2'):
    N = torch.zeros((8, 8, 8), device=device, dtype=DTYPE)
    def add(a, b, c, v):
        N[a, b, c] = v
        N[b, a, c] = -v
    if algebra == 'A1':
        add(0,1,2,1); add(0,2,1,-1); add(1,2,0,1)
    elif algebra == 'A2':
        add(0,2,2,2);  add(0,3,3,-2)
        add(0,4,4,-1); add(0,5,5,1)
        add(0,6,6,1);  add(0,7,7,-1)
        add(1,2,2,-1); add(1,3,3,1)
        add(1,4,4,2);  add(1,5,5,-2)
        add(1,6,6,1);  add(1,7,7,-1)
        add(2,4,6,1);  add(2,7,5,-1)
        add(4,7,3,1);  add(2,3,0,1)
        add(4,5,1,1);  add(6,7,0,1)
        add(6,7,1,1)
    return N

def gell_mann_f():
    f = np.zeros((8, 8, 8))
    entries = [
        (0,1,2, 1.0), (0,3,6, 0.5), (0,4,5, -0.5),
        (1,3,5, 0.5), (1,4,6, 0.5), (2,3,4, 0.5),
        (2,5,6, -0.5), (3,4,7, np.sqrt(3)/2), (5,6,7, np.sqrt(3)/2)
    ]
    for a,b,c,val in entries:
        f[a,b,c] = val; f[b,c,a] = val; f[c,a,b] = val
        f[a,c,b] = -val; f[c,b,a] = -val; f[b,a,c] = -val
    return f

def all_reference_tensors():
    return {'A1': chevalley_tensor('A1'), 'A2': chevalley_tensor('A2')}

# ============================================================================
# 9. Métricas algébricas e classificação
# ============================================================================
def jacobi_error_relative_tensor(F):
    t1 = torch.einsum('abd,dce->abce', F, F)
    t2 = torch.einsum('bcd,dae->abce', F, F)
    t3 = torch.einsum('cad,dbe->abce', F, F)
    J = t1 + t2 + t3
    return J.pow(2).mean().item() / (F.pow(2).mean().item()**2 + 1e-8)

def jacobi_error(F):
    t1 = torch.einsum('abd,dce->abce', F, F)
    t2 = torch.einsum('bcd,dae->abce', F, F)
    t3 = torch.einsum('cad,dbe->abce', F, F)
    return (t1 + t2 + t3).pow(2).mean()

def closure_error_diff(F_lie, alpha):
    brackets = torch.einsum('ai,bj,ijk->abk', alpha, alpha, F_lie)
    coef = torch.einsum('ai,abk->ibk', alpha, brackets)
    proj = torch.einsum('ai,ibk->abk', alpha, coef)
    return (brackets - proj).pow(2).mean()

def compute_killing_like(F):
    return torch.einsum('acd,bcd->ab', F, F)

def active_dimension(Ftilde, ratio_threshold=5.0, abs_threshold=1e-3):
    Kf = torch.einsum('acd,bcd->ab', Ftilde, Ftilde)
    vals, vecs = torch.linalg.eigh(Kf)
    idx = torch.argsort(vals.abs(), descending=True)
    vals, vecs = vals[idx], vecs[:, idx]
    ratios = vals.abs()[:-1] / (vals.abs()[1:] + 1e-8)
    if (ratios > ratio_threshold).any():
        d = (ratios > ratio_threshold).int().argmax().item() + 1
    else:
        d = (vals.abs() > abs_threshold * vals.abs().max()).sum().item()
    return max(d, 1), vals, vecs

def classify_algebra(Ftilde, ratio_threshold=5.0, abs_threshold=1e-3,
                     epochs_align=500, n_starts=5):
    d_active, vals, vecs = active_dimension(Ftilde, ratio_threshold, abs_threshold)
    V = vecs[:, :d_active]
    F_active = torch.einsum('ia,jb,kc,abc->ijk', V.T, V.T, V.T, Ftilde)
    refs = all_reference_tensors()
    best, best_score = None, float('inf')
    results = {}
    for name, N_ref in refs.items():
        d_ref = N_ref.shape[0]
        if d_active < d_ref:
            results[name] = {'score': float('inf'), 'note': f'dim mismatch'}
            continue
        F_comp = F_active if d_active == d_ref else F_active
        N_comp = N_ref if d_active == d_ref else \
                 torch.einsum('ia,jb,kc,abc->ijk', vecs[:d_ref,:d_active].T,
                              vecs[:d_ref,:d_active].T, vecs[:d_ref,:d_active].T, N_ref)
        dim = F_comp.shape[0]
        best_dist = float('inf')
        for _ in range(n_starts):
            P = torch.nn.Parameter(torch.eye(dim, device=device, dtype=DTYPE))
            opt_P = optim.Adam([P], lr=0.01)
            for _ in range(epochs_align):
                opt_P.zero_grad()
                Q, _ = torch.linalg.qr(P + 1e-6 * torch.eye(dim, device=device, dtype=DTYPE))
                N_trans = torch.einsum('ai,bj,kc,ijk->abc', Q, Q, Q.T, N_comp)
                loss = (F_comp - N_trans).pow(2).mean()
                loss.backward()
                opt_P.step()
            with torch.no_grad():
                Q, _ = torch.linalg.qr(P + 1e-6 * torch.eye(dim, device=device, dtype=DTYPE))
                N_trans = torch.einsum('ai,bj,kc,ijk->abc', Q, Q, Q.T, N_comp)
                dist = (F_comp - N_trans).pow(2).mean().item()
                if dist < best_dist:
                    best_dist = dist
        results[name] = {'score': best_dist}
        if best_dist < best_score:
            best_score = best_dist
            best = name
    return best, best_score, results, d_active

def identify_algebra(C_red, jac_shuffle=None):
    """
    Validação final. Se jac_shuffle for fornecido, compara a violação de Jacobi
    com a linha de base e modula a classificação quasi‑Lie em função da razão.
    """
    dim = C_red.shape[0]
    print(f"\n=== IDENTIFICAÇÃO DE ÁLGEBRA (d={dim}) ===")
    antisym = np.max(np.abs(C_red + C_red.transpose(1,0,2)))
    print(f"Erro de antissimetria: {antisym:.2e}")

    J = np.zeros((dim, dim, dim, dim))
    for a in range(dim):
        for b in range(dim):
            for c in range(dim):
                for d_idx in range(dim):
                    s = 0.0
                    for e in range(dim):
                        s += (C_red[a,b,e] * C_red[e,c,d_idx] +
                              C_red[b,c,e] * C_red[e,a,d_idx] +
                              C_red[c,a,e] * C_red[e,b,d_idx])
                    J[a,b,c,d_idx] = s
    jac_norm = np.sqrt(np.sum(J**2))
    C_norm = np.sqrt(np.sum(C_red**2))
    jac_rel = jac_norm / (C_norm**2 + 1e-12)
    print(f"Jacobi relativo: {jac_rel:.4e}")

    if jac_shuffle is not None:
        ratio = jac_rel / (jac_shuffle + 1e-12)
        print(f"Razão Jacobi / shuffle: {ratio:.2f}")
    else:
        ratio = None

    if dim == 8:
        F_target = gell_mann_f()
        F_input = C_red / (np.linalg.norm(C_red) + 1e-12)
        F_target = F_target / (np.linalg.norm(F_target) + 1e-12)
        T = torch.eye(dim, dtype=DTYPE, device=device, requires_grad=True)
        F_target_t = torch.tensor(F_target, dtype=DTYPE, device=device)
        F_input_t = torch.tensor(F_input, dtype=DTYPE, device=device)
        opt = torch.optim.Adam([T], lr=1e-2)
        best_dist = float('inf')
        for _ in range(500):
            opt.zero_grad()
            Q, _ = torch.linalg.qr(T)
            F_trans = torch.einsum('ai,bj,ck,ijk->abc', Q, Q, Q, F_target_t)
            loss = ((F_trans - F_input_t)**2).mean()
            loss.backward()
            opt.step()
            with torch.no_grad():
                dist = loss.item()
                if dist < best_dist:
                    best_dist = dist
        print(f"Distância Procrustes para SU(3) (Gell‑Mann): {best_dist:.4e}")
        if best_dist < 1e-4:
            print(">>> ESTRUTURA COMPATÍVEL COM SU(3) (base de Gell‑Mann)")
        elif best_dist < 1e-2:
            print(">>> Aproximação parcial de SU(3)")
        else:
            print(">>> NÃO é compatível com SU(3) canónico")
    else:
        best_dist = None
        print(f"Dimensão {dim} ≠ 8. Não é possível comparar com SU(3).")

    if antisym < 1e-12 and jac_rel < 1e-3:
        print(">>> Estrutura satisfaz os axiomas de álgebra de Lie.")
        if dim == 8:
            print(">>> Pela classificação de Cartan‑Killing, a única álgebra simples compacta de dim 8 é su(3).")
    else:
        if antisym >= 1e-12:
            print(">>> ATENÇÃO: Violação de antissimetria.")
        if jac_rel >= 1e-3:
            if ratio is not None and ratio < 1.0:
                print(f">>> Estrutura quasi‑Lie emergente (Jacobi {jac_rel:.2e}, razão vs. shuffle {ratio:.2f}).")
            else:
                print(f">>> ATENÇÃO: Violação de Jacobi ({jac_rel:.2e}). Estrutura quasi‑Lie emergente.")
    return antisym, jac_rel, best_dist if dim==8 else None

# ============================================================================
# 10. Diagnóstico de estabilidade e validação
# ============================================================================
def dimension_stability(Ftilde, ratio_range=(3.0, 10.0), abs_range=(1e-4, 1e-2)):
    results = {}
    for ratio_th in np.linspace(*ratio_range, 5):
        for abs_th in np.logspace(np.log10(abs_range[0]), np.log10(abs_range[1]), 5):
            d, _, _ = active_dimension(Ftilde, ratio_th, abs_th)
            results[(ratio_th, abs_th)] = d
    return results

def full_validation(S_series, C_red, seed=None):
    omega = poisson_bracket_omega(S_series)
    jac_real = poisson_jacobi_direct(omega, C_red)
    jac_shuffle = shuffle_baseline(S_series, seed=seed)
    ratio = jac_real / (jac_shuffle + 1e-12)
    print(f"Jacobi real:     {jac_real:.4e}")
    print(f"Jacobi shuffle:  {jac_shuffle:.4e}")
    print(f"Razão J/shuffle: {ratio:.2f}")
    if ratio < 1.0:
        print(">>> O sinal quasi‑Lie é mais forte do que a linha de base.")
    else:
        print(">>> ATENÇÃO: A violação de Jacobi não se distingue da linha de base.")
    return jac_real, jac_shuffle, ratio

# ============================================================================
# 11. Sweep de parâmetros (mapa de fase)
# ============================================================================
def sweep_parameters(param_grid, sizes, T_equil, T_sample, snap_interval,
                     max_cycles=50, seed=42):
    """
    Varre uma grelha de parâmetros e devolve as métricas de Jacobi e
    rank efectivo para cada ponto.  A dimensão do subespaço PCA é determinada
    automaticamente pela dimensão ativa da forma de Killing de C_red.
    """
    results = []
    for params in param_grid:
        print(f"Testando parâmetros: {params}")
        graphs_raw = generate_graphs(sizes, m=2, seed=seed)
        G_global, node_graph, nodes_per_graph = couple_graphs(graphs_raw, 5, seed)
        snapshots, _, _ = run_soc_simulation(
            G_global, node_graph, nodes_per_graph,
            EPSILON_CROSS=params.get('EPSILON_CROSS', 0.01),
            T_equil=T_equil, T_sample=T_sample, snap_interval=snap_interval,
            dissipative=params.get('dissipative', True),
            frustration=params.get('frustration', False),
            tear_prob=params.get('tear_prob', 0.0),
            inversion_prob=params.get('inversion_prob', 0.3),
            add_edge_prob=params.get('add_edge_prob', 0.0),
            competition_strength=params.get('competition_strength', 0.0),
            max_avalanche_size=params.get('max_avalanche_size', None),
            seed=seed
        )
        cycles_list = [find_fundamental_cycles(G) for G in graphs_raw]
        clusters, all_cycles, cycle_to_graph = build_clusters(cycles_list, max_per_graph)
        edge_maps = build_edge_maps(all_cycles)
        S_series, F_raw, g, F_lie, offsets = build_SOC_tensors(
            snapshots, clusters, all_cycles, cycle_to_graph, edge_maps,
            EPSILON_BLOCK=params.get('EPSILON_BLOCK', 0.01)
        )
        # Normalização Z‑score e PCA dinâmico
        S_mean = S_series.mean(axis=0)
        S_std = S_series.std(axis=0) + 1e-12
        S_norm = (S_series - S_mean) / S_std
        Cov_S = np.cov(S_norm.T)
        eigvals_cov, eigvecs_cov = np.linalg.eigh(Cov_S)
        idx_cov = np.argsort(eigvals_cov)[::-1]

        # Estimar C no espaço completo (K pode ser grande) e determinar dimensão activa
        omega_full = poisson_bracket_omega(S_norm)
        C_full = estimate_derivatives_C(S_norm)
        F_full = torch.tensor(C_full, dtype=DTYPE, device=device)
        d_active, _, _ = active_dimension(F_full, ratio_threshold=5.0, abs_threshold=1e-3)
        d_proj = min(d_active, len(idx_cov))   # nunca exceder o número de componentes

        # Projecção para a dimensão dinâmica
        V_pca = eigvecs_cov[:, idx_cov[:d_proj]]
        S_red = (S_norm - S_norm.mean(axis=0)) @ V_pca

        omega_red = poisson_bracket_omega(S_red)
        C_red = estimate_derivatives_C(S_red)
        J_poisson = poisson_jacobi_direct(omega_red, C_red)

        F_tensor_red = torch.tensor(C_red.copy(), dtype=DTYPE, device=device)
        K_red = torch.einsum('acd,bcd->ab', F_tensor_red, F_tensor_red)
        eigvals_K, _ = torch.linalg.eigh(K_red)
        rank_eff = (torch.abs(eigvals_K) > 1e-6).sum().item()

        results.append({**params, 'J_poisson': J_poisson, 'rank_eff': rank_eff,
                        'd_active': d_active, 'd_proj': d_proj})
    return results